(cl:in-package imc_ros_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LAT-VAL
          LAT
          LON-VAL
          LON
          HEIGHT-VAL
          HEIGHT
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          PHI-VAL
          PHI
          THETA-VAL
          THETA
          PSI-VAL
          PSI
          U-VAL
          U
          V-VAL
          V
          W-VAL
          W
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          P-VAL
          P
          Q-VAL
          Q
          R-VAL
          R
          DEPTH-VAL
          DEPTH
          ALT-VAL
          ALT
))