(cl:in-package imc_ros_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          VALIDITY-VAL
          VALIDITY
          TYPE-VAL
          TYPE
          UTC_YEAR-VAL
          UTC_YEAR
          UTC_MONTH-VAL
          UTC_MONTH
          UTC_DAY-VAL
          UTC_DAY
          UTC_TIME-VAL
          UTC_TIME
          LAT-VAL
          LAT
          LON-VAL
          LON
          HEIGHT-VAL
          HEIGHT
          SATELLLITES-VAL
          SATELLLITES
          COG-VAL
          COG
          SOG-VAL
          SOG
          HDOP-VAL
          HDOP
          VDOP-VAL
          VDOP
          HACC-VAL
          HACC
          VACC-VAL
          VACC
))