(cl:in-package imc_ros_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          PHI-VAL
          PHI
          THETA-VAL
          THETA
          PSI-VAL
          PSI
          P-VAL
          P
          Q-VAL
          Q
          R-VAL
          R
          U-VAL
          U
          V-VAL
          V
          W-VAL
          W
          BIAS_PSI-VAL
          BIAS_PSI
          BIAS_R-VAL
          BIAS_R
))