# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from minerva2_iface/Forcevector.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Forcevector(genpy.Message):
  _md5sum = "0e5bbf4247b7e2801d320d0defabc11e"
  _type = "minerva2_iface/Forcevector"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
std_msgs/Float32 fx
std_msgs/Float32 fy
std_msgs/Float32 fz
std_msgs/Float32 froll
std_msgs/Float32 fpitch
std_msgs/Float32 fyaw

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: std_msgs/Float32
float32 data"""
  __slots__ = ['header','fx','fy','fz','froll','fpitch','fyaw']
  _slot_types = ['std_msgs/Header','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,fx,fy,fz,froll,fpitch,fyaw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Forcevector, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.fx is None:
        self.fx = std_msgs.msg.Float32()
      if self.fy is None:
        self.fy = std_msgs.msg.Float32()
      if self.fz is None:
        self.fz = std_msgs.msg.Float32()
      if self.froll is None:
        self.froll = std_msgs.msg.Float32()
      if self.fpitch is None:
        self.fpitch = std_msgs.msg.Float32()
      if self.fyaw is None:
        self.fyaw = std_msgs.msg.Float32()
    else:
      self.header = std_msgs.msg.Header()
      self.fx = std_msgs.msg.Float32()
      self.fy = std_msgs.msg.Float32()
      self.fz = std_msgs.msg.Float32()
      self.froll = std_msgs.msg.Float32()
      self.fpitch = std_msgs.msg.Float32()
      self.fyaw = std_msgs.msg.Float32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6f().pack(_x.fx.data, _x.fy.data, _x.fz.data, _x.froll.data, _x.fpitch.data, _x.fyaw.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.fx is None:
        self.fx = std_msgs.msg.Float32()
      if self.fy is None:
        self.fy = std_msgs.msg.Float32()
      if self.fz is None:
        self.fz = std_msgs.msg.Float32()
      if self.froll is None:
        self.froll = std_msgs.msg.Float32()
      if self.fpitch is None:
        self.fpitch = std_msgs.msg.Float32()
      if self.fyaw is None:
        self.fyaw = std_msgs.msg.Float32()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.fx.data, _x.fy.data, _x.fz.data, _x.froll.data, _x.fpitch.data, _x.fyaw.data,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6f().pack(_x.fx.data, _x.fy.data, _x.fz.data, _x.froll.data, _x.fpitch.data, _x.fyaw.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.fx is None:
        self.fx = std_msgs.msg.Float32()
      if self.fy is None:
        self.fy = std_msgs.msg.Float32()
      if self.fz is None:
        self.fz = std_msgs.msg.Float32()
      if self.froll is None:
        self.froll = std_msgs.msg.Float32()
      if self.fpitch is None:
        self.fpitch = std_msgs.msg.Float32()
      if self.fyaw is None:
        self.fyaw = std_msgs.msg.Float32()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.fx.data, _x.fy.data, _x.fz.data, _x.froll.data, _x.fpitch.data, _x.fyaw.data,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
