// Generated by gencpp from file imc_ros_msgs/Header.msg
// DO NOT EDIT!


#ifndef IMC_ROS_MSGS_MESSAGE_HEADER_H
#define IMC_ROS_MSGS_MESSAGE_HEADER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/UInt16.h>
#include <std_msgs/UInt16.h>
#include <std_msgs/UInt16.h>
#include <std_msgs/Float64.h>
#include <std_msgs/UInt16.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/UInt16.h>
#include <std_msgs/UInt8.h>

namespace imc_ros_msgs
{
template <class ContainerAllocator>
struct Header_
{
  typedef Header_<ContainerAllocator> Type;

  Header_()
    : rosheader()
    , sync()
    , mgid()
    , size()
    , timestamp()
    , src()
    , src_ent()
    , dst()
    , dst_ent()  {
    }
  Header_(const ContainerAllocator& _alloc)
    : rosheader(_alloc)
    , sync(_alloc)
    , mgid(_alloc)
    , size(_alloc)
    , timestamp(_alloc)
    , src(_alloc)
    , src_ent(_alloc)
    , dst(_alloc)
    , dst_ent(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _rosheader_type;
  _rosheader_type rosheader;

   typedef  ::std_msgs::UInt16_<ContainerAllocator>  _sync_type;
  _sync_type sync;

   typedef  ::std_msgs::UInt16_<ContainerAllocator>  _mgid_type;
  _mgid_type mgid;

   typedef  ::std_msgs::UInt16_<ContainerAllocator>  _size_type;
  _size_type size;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _timestamp_type;
  _timestamp_type timestamp;

   typedef  ::std_msgs::UInt16_<ContainerAllocator>  _src_type;
  _src_type src;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _src_ent_type;
  _src_ent_type src_ent;

   typedef  ::std_msgs::UInt16_<ContainerAllocator>  _dst_type;
  _dst_type dst;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _dst_ent_type;
  _dst_ent_type dst_ent;





  typedef boost::shared_ptr< ::imc_ros_msgs::Header_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imc_ros_msgs::Header_<ContainerAllocator> const> ConstPtr;

}; // struct Header_

typedef ::imc_ros_msgs::Header_<std::allocator<void> > Header;

typedef boost::shared_ptr< ::imc_ros_msgs::Header > HeaderPtr;
typedef boost::shared_ptr< ::imc_ros_msgs::Header const> HeaderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imc_ros_msgs::Header_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imc_ros_msgs::Header_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imc_ros_msgs::Header_<ContainerAllocator1> & lhs, const ::imc_ros_msgs::Header_<ContainerAllocator2> & rhs)
{
  return lhs.rosheader == rhs.rosheader &&
    lhs.sync == rhs.sync &&
    lhs.mgid == rhs.mgid &&
    lhs.size == rhs.size &&
    lhs.timestamp == rhs.timestamp &&
    lhs.src == rhs.src &&
    lhs.src_ent == rhs.src_ent &&
    lhs.dst == rhs.dst &&
    lhs.dst_ent == rhs.dst_ent;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imc_ros_msgs::Header_<ContainerAllocator1> & lhs, const ::imc_ros_msgs::Header_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imc_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::imc_ros_msgs::Header_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imc_ros_msgs::Header_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imc_ros_msgs::Header_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imc_ros_msgs::Header_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imc_ros_msgs::Header_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imc_ros_msgs::Header_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imc_ros_msgs::Header_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f599b646bbd90db766bafb08706c85c7";
  }

  static const char* value(const ::imc_ros_msgs::Header_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf599b646bbd90db7ULL;
  static const uint64_t static_value2 = 0x66bafb08706c85c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::imc_ros_msgs::Header_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imc_ros_msgs/Header";
  }

  static const char* value(const ::imc_ros_msgs::Header_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imc_ros_msgs::Header_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header rosheader\n"
"std_msgs/UInt16 sync\n"
"std_msgs/UInt16 mgid\n"
"std_msgs/UInt16 size\n"
"std_msgs/Float64 timestamp\n"
"std_msgs/UInt16 src\n"
"std_msgs/UInt8 src_ent\n"
"std_msgs/UInt16 dst\n"
"std_msgs/UInt8 dst_ent\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt16\n"
"uint16 data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: std_msgs/UInt8\n"
"uint8 data\n"
;
  }

  static const char* value(const ::imc_ros_msgs::Header_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imc_ros_msgs::Header_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rosheader);
      stream.next(m.sync);
      stream.next(m.mgid);
      stream.next(m.size);
      stream.next(m.timestamp);
      stream.next(m.src);
      stream.next(m.src_ent);
      stream.next(m.dst);
      stream.next(m.dst_ent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Header_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imc_ros_msgs::Header_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imc_ros_msgs::Header_<ContainerAllocator>& v)
  {
    s << indent << "rosheader: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.rosheader);
    s << indent << "sync: ";
    s << std::endl;
    Printer< ::std_msgs::UInt16_<ContainerAllocator> >::stream(s, indent + "  ", v.sync);
    s << indent << "mgid: ";
    s << std::endl;
    Printer< ::std_msgs::UInt16_<ContainerAllocator> >::stream(s, indent + "  ", v.mgid);
    s << indent << "size: ";
    s << std::endl;
    Printer< ::std_msgs::UInt16_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
    s << indent << "timestamp: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.timestamp);
    s << indent << "src: ";
    s << std::endl;
    Printer< ::std_msgs::UInt16_<ContainerAllocator> >::stream(s, indent + "  ", v.src);
    s << indent << "src_ent: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.src_ent);
    s << indent << "dst: ";
    s << std::endl;
    Printer< ::std_msgs::UInt16_<ContainerAllocator> >::stream(s, indent + "  ", v.dst);
    s << indent << "dst_ent: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.dst_ent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMC_ROS_MSGS_MESSAGE_HEADER_H
