// Generated by gencpp from file imc_ros_msgs/PlanControlState.msg
// DO NOT EDIT!


#ifndef IMC_ROS_MSGS_MESSAGE_PLANCONTROLSTATE_H
#define IMC_ROS_MSGS_MESSAGE_PLANCONTROLSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <imc_ros_msgs/Header.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/String.h>
#include <std_msgs/Int32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/String.h>
#include <std_msgs/UInt16.h>
#include <std_msgs/Int32.h>
#include <std_msgs/UInt8.h>

namespace imc_ros_msgs
{
template <class ContainerAllocator>
struct PlanControlState_
{
  typedef PlanControlState_<ContainerAllocator> Type;

  PlanControlState_()
    : header()
    , state()
    , plan_id()
    , plan_eta()
    , plan_progress()
    , man_id()
    , man_type()
    , man_eta()
    , last_outcome()  {
    }
  PlanControlState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(_alloc)
    , plan_id(_alloc)
    , plan_eta(_alloc)
    , plan_progress(_alloc)
    , man_id(_alloc)
    , man_type(_alloc)
    , man_eta(_alloc)
    , last_outcome(_alloc)  {
  (void)_alloc;
    }



   typedef  ::imc_ros_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _state_type;
  _state_type state;

   typedef  ::std_msgs::String_<ContainerAllocator>  _plan_id_type;
  _plan_id_type plan_id;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _plan_eta_type;
  _plan_eta_type plan_eta;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _plan_progress_type;
  _plan_progress_type plan_progress;

   typedef  ::std_msgs::String_<ContainerAllocator>  _man_id_type;
  _man_id_type man_id;

   typedef  ::std_msgs::UInt16_<ContainerAllocator>  _man_type_type;
  _man_type_type man_type;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _man_eta_type;
  _man_eta_type man_eta;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _last_outcome_type;
  _last_outcome_type last_outcome;





  typedef boost::shared_ptr< ::imc_ros_msgs::PlanControlState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imc_ros_msgs::PlanControlState_<ContainerAllocator> const> ConstPtr;

}; // struct PlanControlState_

typedef ::imc_ros_msgs::PlanControlState_<std::allocator<void> > PlanControlState;

typedef boost::shared_ptr< ::imc_ros_msgs::PlanControlState > PlanControlStatePtr;
typedef boost::shared_ptr< ::imc_ros_msgs::PlanControlState const> PlanControlStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imc_ros_msgs::PlanControlState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imc_ros_msgs::PlanControlState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imc_ros_msgs::PlanControlState_<ContainerAllocator1> & lhs, const ::imc_ros_msgs::PlanControlState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state &&
    lhs.plan_id == rhs.plan_id &&
    lhs.plan_eta == rhs.plan_eta &&
    lhs.plan_progress == rhs.plan_progress &&
    lhs.man_id == rhs.man_id &&
    lhs.man_type == rhs.man_type &&
    lhs.man_eta == rhs.man_eta &&
    lhs.last_outcome == rhs.last_outcome;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imc_ros_msgs::PlanControlState_<ContainerAllocator1> & lhs, const ::imc_ros_msgs::PlanControlState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imc_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::imc_ros_msgs::PlanControlState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imc_ros_msgs::PlanControlState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imc_ros_msgs::PlanControlState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imc_ros_msgs::PlanControlState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imc_ros_msgs::PlanControlState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imc_ros_msgs::PlanControlState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imc_ros_msgs::PlanControlState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37c774ecf5519b9a486a42a0755de1f7";
  }

  static const char* value(const ::imc_ros_msgs::PlanControlState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37c774ecf5519b9aULL;
  static const uint64_t static_value2 = 0x486a42a0755de1f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::imc_ros_msgs::PlanControlState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imc_ros_msgs/PlanControlState";
  }

  static const char* value(const ::imc_ros_msgs::PlanControlState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imc_ros_msgs::PlanControlState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imc_ros_msgs/Header header\n"
"std_msgs/UInt8 state\n"
"std_msgs/String plan_id\n"
"std_msgs/Int32 plan_eta\n"
"std_msgs/Float32 plan_progress\n"
"std_msgs/String man_id\n"
"std_msgs/UInt16 man_type\n"
"std_msgs/Int32 man_eta\n"
"std_msgs/UInt8 last_outcome #See IMC.xml\n"
"\n"
"\n"
"================================================================================\n"
"MSG: imc_ros_msgs/Header\n"
"std_msgs/Header rosheader\n"
"std_msgs/UInt16 sync\n"
"std_msgs/UInt16 mgid\n"
"std_msgs/UInt16 size\n"
"std_msgs/Float64 timestamp\n"
"std_msgs/UInt16 src\n"
"std_msgs/UInt8 src_ent\n"
"std_msgs/UInt16 dst\n"
"std_msgs/UInt8 dst_ent\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt16\n"
"uint16 data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: std_msgs/UInt8\n"
"uint8 data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::imc_ros_msgs::PlanControlState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imc_ros_msgs::PlanControlState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.plan_id);
      stream.next(m.plan_eta);
      stream.next(m.plan_progress);
      stream.next(m.man_id);
      stream.next(m.man_type);
      stream.next(m.man_eta);
      stream.next(m.last_outcome);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanControlState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imc_ros_msgs::PlanControlState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imc_ros_msgs::PlanControlState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::imc_ros_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
    s << indent << "plan_id: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.plan_id);
    s << indent << "plan_eta: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.plan_eta);
    s << indent << "plan_progress: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.plan_progress);
    s << indent << "man_id: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.man_id);
    s << indent << "man_type: ";
    s << std::endl;
    Printer< ::std_msgs::UInt16_<ContainerAllocator> >::stream(s, indent + "  ", v.man_type);
    s << indent << "man_eta: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.man_eta);
    s << indent << "last_outcome: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.last_outcome);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMC_ROS_MSGS_MESSAGE_PLANCONTROLSTATE_H
