// Generated by gencpp from file imc_ros_msgs/Reference.msg
// DO NOT EDIT!


#ifndef IMC_ROS_MSGS_MESSAGE_REFERENCE_H
#define IMC_ROS_MSGS_MESSAGE_REFERENCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <imc_ros_msgs/Header.h>
#include <std_msgs/UInt8.h>
#include <imc_ros_msgs/DesiredSpeed.h>
#include <imc_ros_msgs/DesiredZ.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float32.h>

namespace imc_ros_msgs
{
template <class ContainerAllocator>
struct Reference_
{
  typedef Reference_<ContainerAllocator> Type;

  Reference_()
    : header()
    , flags()
    , speed()
    , z()
    , lat()
    , lon()
    , radius()  {
    }
  Reference_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , flags(_alloc)
    , speed(_alloc)
    , z(_alloc)
    , lat(_alloc)
    , lon(_alloc)
    , radius(_alloc)  {
  (void)_alloc;
    }



   typedef  ::imc_ros_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _flags_type;
  _flags_type flags;

   typedef  ::imc_ros_msgs::DesiredSpeed_<ContainerAllocator>  _speed_type;
  _speed_type speed;

   typedef  ::imc_ros_msgs::DesiredZ_<ContainerAllocator>  _z_type;
  _z_type z;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _lat_type;
  _lat_type lat;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _lon_type;
  _lon_type lon;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::imc_ros_msgs::Reference_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imc_ros_msgs::Reference_<ContainerAllocator> const> ConstPtr;

}; // struct Reference_

typedef ::imc_ros_msgs::Reference_<std::allocator<void> > Reference;

typedef boost::shared_ptr< ::imc_ros_msgs::Reference > ReferencePtr;
typedef boost::shared_ptr< ::imc_ros_msgs::Reference const> ReferenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imc_ros_msgs::Reference_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imc_ros_msgs::Reference_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imc_ros_msgs::Reference_<ContainerAllocator1> & lhs, const ::imc_ros_msgs::Reference_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.flags == rhs.flags &&
    lhs.speed == rhs.speed &&
    lhs.z == rhs.z &&
    lhs.lat == rhs.lat &&
    lhs.lon == rhs.lon &&
    lhs.radius == rhs.radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imc_ros_msgs::Reference_<ContainerAllocator1> & lhs, const ::imc_ros_msgs::Reference_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imc_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::imc_ros_msgs::Reference_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imc_ros_msgs::Reference_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imc_ros_msgs::Reference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imc_ros_msgs::Reference_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imc_ros_msgs::Reference_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imc_ros_msgs::Reference_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imc_ros_msgs::Reference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fd9aae03cf719e4a18ef0ec94ff4aca";
  }

  static const char* value(const ::imc_ros_msgs::Reference_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fd9aae03cf719e4ULL;
  static const uint64_t static_value2 = 0xa18ef0ec94ff4acaULL;
};

template<class ContainerAllocator>
struct DataType< ::imc_ros_msgs::Reference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imc_ros_msgs/Reference";
  }

  static const char* value(const ::imc_ros_msgs::Reference_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imc_ros_msgs::Reference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imc_ros_msgs/Header header\n"
"std_msgs/UInt8 flags \n"
"#      //! Use Location Reference.\n"
"#      FLAG_LOCATION = 0x01,\n"
"#      //! Use Speed Reference.\n"
"#      FLAG_SPEED = 0x02,\n"
"#      //! Use Z Reference.\n"
"#      FLAG_Z = 0x04,\n"
"#      //! Use Radius Reference.\n"
"#      FLAG_RADIUS = 0x08,\n"
"#      //! Use this Reference as Start Position for PathControler.\n"
"#      FLAG_START_POINT = 0x10,\n"
"#      //! Use Current Position as Start Position for PathControler.\n"
"#      FLAG_DIRECT = 0x20,\n"
"#      //! Flag Maneuver Completion.\n"
"#      FLAG_MANDONE = 0x80\n"
"imc_ros_msgs/DesiredSpeed speed\n"
"imc_ros_msgs/DesiredZ z\n"
"std_msgs/Float64 lat \n"
"std_msgs/Float64 lon\n"
"std_msgs/Float32 radius\n"
"\n"
"================================================================================\n"
"MSG: imc_ros_msgs/Header\n"
"std_msgs/Header rosheader\n"
"std_msgs/UInt16 sync\n"
"std_msgs/UInt16 mgid\n"
"std_msgs/UInt16 size\n"
"std_msgs/Float64 timestamp\n"
"std_msgs/UInt16 src\n"
"std_msgs/UInt8 src_ent\n"
"std_msgs/UInt16 dst\n"
"std_msgs/UInt8 dst_ent\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt16\n"
"uint16 data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: std_msgs/UInt8\n"
"uint8 data\n"
"\n"
"================================================================================\n"
"MSG: imc_ros_msgs/DesiredSpeed\n"
"imc_ros_msgs/Header header\n"
"std_msgs/Float64 value\n"
"std_msgs/UInt8 speed_units #Enumerated list, see IMC.xml\n"
"\n"
"================================================================================\n"
"MSG: imc_ros_msgs/DesiredZ\n"
"imc_ros_msgs/Header header\n"
"std_msgs/Float32 value #unit [m]\n"
"std_msgs/UInt8 z_units # depth/alt, see IMC.xml 0=none 1=depth 2=alt 3=height\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::imc_ros_msgs::Reference_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imc_ros_msgs::Reference_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.flags);
      stream.next(m.speed);
      stream.next(m.z);
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Reference_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imc_ros_msgs::Reference_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imc_ros_msgs::Reference_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::imc_ros_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "flags: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.flags);
    s << indent << "speed: ";
    s << std::endl;
    Printer< ::imc_ros_msgs::DesiredSpeed_<ContainerAllocator> >::stream(s, indent + "  ", v.speed);
    s << indent << "z: ";
    s << std::endl;
    Printer< ::imc_ros_msgs::DesiredZ_<ContainerAllocator> >::stream(s, indent + "  ", v.z);
    s << indent << "lat: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.lon);
    s << indent << "radius: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMC_ROS_MSGS_MESSAGE_REFERENCE_H
