// Generated by gencpp from file minerva2_iface/Mtipro.msg
// DO NOT EDIT!


#ifndef MINERVA2_IFACE_MESSAGE_MTIPRO_H
#define MINERVA2_IFACE_MESSAGE_MTIPRO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>

namespace minerva2_iface
{
template <class ContainerAllocator>
struct Mtipro_
{
  typedef Mtipro_<ContainerAllocator> Type;

  Mtipro_()
    : header()
    , roll()
    , pitch()
    , yaw()  {
    }
  Mtipro_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , roll(_alloc)
    , pitch(_alloc)
    , yaw(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _roll_type;
  _roll_type roll;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _pitch_type;
  _pitch_type pitch;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::minerva2_iface::Mtipro_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::minerva2_iface::Mtipro_<ContainerAllocator> const> ConstPtr;

}; // struct Mtipro_

typedef ::minerva2_iface::Mtipro_<std::allocator<void> > Mtipro;

typedef boost::shared_ptr< ::minerva2_iface::Mtipro > MtiproPtr;
typedef boost::shared_ptr< ::minerva2_iface::Mtipro const> MtiproConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::minerva2_iface::Mtipro_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::minerva2_iface::Mtipro_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::minerva2_iface::Mtipro_<ContainerAllocator1> & lhs, const ::minerva2_iface::Mtipro_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::minerva2_iface::Mtipro_<ContainerAllocator1> & lhs, const ::minerva2_iface::Mtipro_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace minerva2_iface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::minerva2_iface::Mtipro_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minerva2_iface::Mtipro_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::minerva2_iface::Mtipro_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::minerva2_iface::Mtipro_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minerva2_iface::Mtipro_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minerva2_iface::Mtipro_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::minerva2_iface::Mtipro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ecf5f4cc2cc1e3431a655ba24a6201ff";
  }

  static const char* value(const ::minerva2_iface::Mtipro_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xecf5f4cc2cc1e343ULL;
  static const uint64_t static_value2 = 0x1a655ba24a6201ffULL;
};

template<class ContainerAllocator>
struct DataType< ::minerva2_iface::Mtipro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "minerva2_iface/Mtipro";
  }

  static const char* value(const ::minerva2_iface::Mtipro_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::minerva2_iface::Mtipro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"std_msgs/Float32 roll\n"
"std_msgs/Float32 pitch\n"
"std_msgs/Float32 yaw\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::minerva2_iface::Mtipro_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::minerva2_iface::Mtipro_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mtipro_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::minerva2_iface::Mtipro_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::minerva2_iface::Mtipro_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "roll: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINERVA2_IFACE_MESSAGE_MTIPRO_H
