// Generated by gencpp from file minerva2_iface/Navipac.msg
// DO NOT EDIT!


#ifndef MINERVA2_IFACE_MESSAGE_NAVIPAC_H
#define MINERVA2_IFACE_MESSAGE_NAVIPAC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>

namespace minerva2_iface
{
template <class ContainerAllocator>
struct Navipac_
{
  typedef Navipac_<ContainerAllocator> Type;

  Navipac_()
    : header()
    , north()
    , east()
    , down()
    , u()
    , v()
    , w()  {
    }
  Navipac_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , north(_alloc)
    , east(_alloc)
    , down(_alloc)
    , u(_alloc)
    , v(_alloc)
    , w(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _north_type;
  _north_type north;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _east_type;
  _east_type east;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _down_type;
  _down_type down;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _u_type;
  _u_type u;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _v_type;
  _v_type v;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::minerva2_iface::Navipac_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::minerva2_iface::Navipac_<ContainerAllocator> const> ConstPtr;

}; // struct Navipac_

typedef ::minerva2_iface::Navipac_<std::allocator<void> > Navipac;

typedef boost::shared_ptr< ::minerva2_iface::Navipac > NavipacPtr;
typedef boost::shared_ptr< ::minerva2_iface::Navipac const> NavipacConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::minerva2_iface::Navipac_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::minerva2_iface::Navipac_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::minerva2_iface::Navipac_<ContainerAllocator1> & lhs, const ::minerva2_iface::Navipac_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.north == rhs.north &&
    lhs.east == rhs.east &&
    lhs.down == rhs.down &&
    lhs.u == rhs.u &&
    lhs.v == rhs.v &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::minerva2_iface::Navipac_<ContainerAllocator1> & lhs, const ::minerva2_iface::Navipac_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace minerva2_iface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::minerva2_iface::Navipac_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minerva2_iface::Navipac_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::minerva2_iface::Navipac_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::minerva2_iface::Navipac_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minerva2_iface::Navipac_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minerva2_iface::Navipac_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::minerva2_iface::Navipac_<ContainerAllocator> >
{
  static const char* value()
  {
    return "526c3ab86598af434d315ff08e79faeb";
  }

  static const char* value(const ::minerva2_iface::Navipac_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x526c3ab86598af43ULL;
  static const uint64_t static_value2 = 0x4d315ff08e79faebULL;
};

template<class ContainerAllocator>
struct DataType< ::minerva2_iface::Navipac_<ContainerAllocator> >
{
  static const char* value()
  {
    return "minerva2_iface/Navipac";
  }

  static const char* value(const ::minerva2_iface::Navipac_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::minerva2_iface::Navipac_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"std_msgs/Float32 north\n"
"std_msgs/Float32 east\n"
"std_msgs/Float32 down\n"
"std_msgs/Float32 u\n"
"std_msgs/Float32 v\n"
"std_msgs/Float32 w \n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::minerva2_iface::Navipac_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::minerva2_iface::Navipac_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.north);
      stream.next(m.east);
      stream.next(m.down);
      stream.next(m.u);
      stream.next(m.v);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Navipac_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::minerva2_iface::Navipac_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::minerva2_iface::Navipac_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "north: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.north);
    s << indent << "east: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.east);
    s << indent << "down: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.down);
    s << indent << "u: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.u);
    s << indent << "v: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.v);
    s << indent << "w: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINERVA2_IFACE_MESSAGE_NAVIPAC_H
