# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from imc_ros_msgs/Header.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Header(genpy.Message):
  _md5sum = "f599b646bbd90db766bafb08706c85c7"
  _type = "imc_ros_msgs/Header"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header rosheader
std_msgs/UInt16 sync
std_msgs/UInt16 mgid
std_msgs/UInt16 size
std_msgs/Float64 timestamp
std_msgs/UInt16 src
std_msgs/UInt8 src_ent
std_msgs/UInt16 dst
std_msgs/UInt8 dst_ent

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: std_msgs/UInt16
uint16 data

================================================================================
MSG: std_msgs/Float64
float64 data
================================================================================
MSG: std_msgs/UInt8
uint8 data
"""
  __slots__ = ['rosheader','sync','mgid','size','timestamp','src','src_ent','dst','dst_ent']
  _slot_types = ['std_msgs/Header','std_msgs/UInt16','std_msgs/UInt16','std_msgs/UInt16','std_msgs/Float64','std_msgs/UInt16','std_msgs/UInt8','std_msgs/UInt16','std_msgs/UInt8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rosheader,sync,mgid,size,timestamp,src,src_ent,dst,dst_ent

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Header, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.rosheader is None:
        self.rosheader = std_msgs.msg.Header()
      if self.sync is None:
        self.sync = std_msgs.msg.UInt16()
      if self.mgid is None:
        self.mgid = std_msgs.msg.UInt16()
      if self.size is None:
        self.size = std_msgs.msg.UInt16()
      if self.timestamp is None:
        self.timestamp = std_msgs.msg.Float64()
      if self.src is None:
        self.src = std_msgs.msg.UInt16()
      if self.src_ent is None:
        self.src_ent = std_msgs.msg.UInt8()
      if self.dst is None:
        self.dst = std_msgs.msg.UInt16()
      if self.dst_ent is None:
        self.dst_ent = std_msgs.msg.UInt8()
    else:
      self.rosheader = std_msgs.msg.Header()
      self.sync = std_msgs.msg.UInt16()
      self.mgid = std_msgs.msg.UInt16()
      self.size = std_msgs.msg.UInt16()
      self.timestamp = std_msgs.msg.Float64()
      self.src = std_msgs.msg.UInt16()
      self.src_ent = std_msgs.msg.UInt8()
      self.dst = std_msgs.msg.UInt16()
      self.dst_ent = std_msgs.msg.UInt8()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.rosheader.seq, _x.rosheader.stamp.secs, _x.rosheader.stamp.nsecs))
      _x = self.rosheader.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3HdHBHB().pack(_x.sync.data, _x.mgid.data, _x.size.data, _x.timestamp.data, _x.src.data, _x.src_ent.data, _x.dst.data, _x.dst_ent.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.rosheader is None:
        self.rosheader = std_msgs.msg.Header()
      if self.sync is None:
        self.sync = std_msgs.msg.UInt16()
      if self.mgid is None:
        self.mgid = std_msgs.msg.UInt16()
      if self.size is None:
        self.size = std_msgs.msg.UInt16()
      if self.timestamp is None:
        self.timestamp = std_msgs.msg.Float64()
      if self.src is None:
        self.src = std_msgs.msg.UInt16()
      if self.src_ent is None:
        self.src_ent = std_msgs.msg.UInt8()
      if self.dst is None:
        self.dst = std_msgs.msg.UInt16()
      if self.dst_ent is None:
        self.dst_ent = std_msgs.msg.UInt8()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.rosheader.seq, _x.rosheader.stamp.secs, _x.rosheader.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.rosheader.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.rosheader.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.sync.data, _x.mgid.data, _x.size.data, _x.timestamp.data, _x.src.data, _x.src_ent.data, _x.dst.data, _x.dst_ent.data,) = _get_struct_3HdHBHB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.rosheader.seq, _x.rosheader.stamp.secs, _x.rosheader.stamp.nsecs))
      _x = self.rosheader.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3HdHBHB().pack(_x.sync.data, _x.mgid.data, _x.size.data, _x.timestamp.data, _x.src.data, _x.src_ent.data, _x.dst.data, _x.dst_ent.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.rosheader is None:
        self.rosheader = std_msgs.msg.Header()
      if self.sync is None:
        self.sync = std_msgs.msg.UInt16()
      if self.mgid is None:
        self.mgid = std_msgs.msg.UInt16()
      if self.size is None:
        self.size = std_msgs.msg.UInt16()
      if self.timestamp is None:
        self.timestamp = std_msgs.msg.Float64()
      if self.src is None:
        self.src = std_msgs.msg.UInt16()
      if self.src_ent is None:
        self.src_ent = std_msgs.msg.UInt8()
      if self.dst is None:
        self.dst = std_msgs.msg.UInt16()
      if self.dst_ent is None:
        self.dst_ent = std_msgs.msg.UInt8()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.rosheader.seq, _x.rosheader.stamp.secs, _x.rosheader.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.rosheader.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.rosheader.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.sync.data, _x.mgid.data, _x.size.data, _x.timestamp.data, _x.src.data, _x.src_ent.data, _x.dst.data, _x.dst_ent.data,) = _get_struct_3HdHBHB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3HdHBHB = None
def _get_struct_3HdHBHB():
    global _struct_3HdHBHB
    if _struct_3HdHBHB is None:
        _struct_3HdHBHB = struct.Struct("<3HdHBHB")
    return _struct_3HdHBHB
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
