# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from imc_ros_msgs/OperationalLimits.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import imc_ros_msgs.msg
import std_msgs.msg

class OperationalLimits(genpy.Message):
  _md5sum = "9f341e7d12deb64a4dcdcdf13b3769d9"
  _type = "imc_ros_msgs/OperationalLimits"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """imc_ros_msgs/Header header
std_msgs/UInt8 mask #See IMC.xml
std_msgs/Float32 max_depth
std_msgs/Float32 min_altitude
std_msgs/Float32 max_altitude
std_msgs/Float32 min_speed
std_msgs/Float32 max_speed
std_msgs/Float32 max_vrate
std_msgs/Float64 lat
std_msgs/Float64 lon
std_msgs/Float32 orientation
std_msgs/Float32 width
std_msgs/Float32 length

================================================================================
MSG: imc_ros_msgs/Header
std_msgs/Header rosheader
std_msgs/UInt16 sync
std_msgs/UInt16 mgid
std_msgs/UInt16 size
std_msgs/Float64 timestamp
std_msgs/UInt16 src
std_msgs/UInt8 src_ent
std_msgs/UInt16 dst
std_msgs/UInt8 dst_ent

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: std_msgs/UInt16
uint16 data

================================================================================
MSG: std_msgs/Float64
float64 data
================================================================================
MSG: std_msgs/UInt8
uint8 data

================================================================================
MSG: std_msgs/Float32
float32 data"""
  __slots__ = ['header','mask','max_depth','min_altitude','max_altitude','min_speed','max_speed','max_vrate','lat','lon','orientation','width','length']
  _slot_types = ['imc_ros_msgs/Header','std_msgs/UInt8','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/Float64','std_msgs/Float64','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,mask,max_depth,min_altitude,max_altitude,min_speed,max_speed,max_vrate,lat,lon,orientation,width,length

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OperationalLimits, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = imc_ros_msgs.msg.Header()
      if self.mask is None:
        self.mask = std_msgs.msg.UInt8()
      if self.max_depth is None:
        self.max_depth = std_msgs.msg.Float32()
      if self.min_altitude is None:
        self.min_altitude = std_msgs.msg.Float32()
      if self.max_altitude is None:
        self.max_altitude = std_msgs.msg.Float32()
      if self.min_speed is None:
        self.min_speed = std_msgs.msg.Float32()
      if self.max_speed is None:
        self.max_speed = std_msgs.msg.Float32()
      if self.max_vrate is None:
        self.max_vrate = std_msgs.msg.Float32()
      if self.lat is None:
        self.lat = std_msgs.msg.Float64()
      if self.lon is None:
        self.lon = std_msgs.msg.Float64()
      if self.orientation is None:
        self.orientation = std_msgs.msg.Float32()
      if self.width is None:
        self.width = std_msgs.msg.Float32()
      if self.length is None:
        self.length = std_msgs.msg.Float32()
    else:
      self.header = imc_ros_msgs.msg.Header()
      self.mask = std_msgs.msg.UInt8()
      self.max_depth = std_msgs.msg.Float32()
      self.min_altitude = std_msgs.msg.Float32()
      self.max_altitude = std_msgs.msg.Float32()
      self.min_speed = std_msgs.msg.Float32()
      self.max_speed = std_msgs.msg.Float32()
      self.max_vrate = std_msgs.msg.Float32()
      self.lat = std_msgs.msg.Float64()
      self.lon = std_msgs.msg.Float64()
      self.orientation = std_msgs.msg.Float32()
      self.width = std_msgs.msg.Float32()
      self.length = std_msgs.msg.Float32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.rosheader.seq, _x.header.rosheader.stamp.secs, _x.header.rosheader.stamp.nsecs))
      _x = self.header.rosheader.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3HdHBH2B6f2d3f().pack(_x.header.sync.data, _x.header.mgid.data, _x.header.size.data, _x.header.timestamp.data, _x.header.src.data, _x.header.src_ent.data, _x.header.dst.data, _x.header.dst_ent.data, _x.mask.data, _x.max_depth.data, _x.min_altitude.data, _x.max_altitude.data, _x.min_speed.data, _x.max_speed.data, _x.max_vrate.data, _x.lat.data, _x.lon.data, _x.orientation.data, _x.width.data, _x.length.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = imc_ros_msgs.msg.Header()
      if self.mask is None:
        self.mask = std_msgs.msg.UInt8()
      if self.max_depth is None:
        self.max_depth = std_msgs.msg.Float32()
      if self.min_altitude is None:
        self.min_altitude = std_msgs.msg.Float32()
      if self.max_altitude is None:
        self.max_altitude = std_msgs.msg.Float32()
      if self.min_speed is None:
        self.min_speed = std_msgs.msg.Float32()
      if self.max_speed is None:
        self.max_speed = std_msgs.msg.Float32()
      if self.max_vrate is None:
        self.max_vrate = std_msgs.msg.Float32()
      if self.lat is None:
        self.lat = std_msgs.msg.Float64()
      if self.lon is None:
        self.lon = std_msgs.msg.Float64()
      if self.orientation is None:
        self.orientation = std_msgs.msg.Float32()
      if self.width is None:
        self.width = std_msgs.msg.Float32()
      if self.length is None:
        self.length = std_msgs.msg.Float32()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.rosheader.seq, _x.header.rosheader.stamp.secs, _x.header.rosheader.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.rosheader.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.rosheader.frame_id = str[start:end]
      _x = self
      start = end
      end += 73
      (_x.header.sync.data, _x.header.mgid.data, _x.header.size.data, _x.header.timestamp.data, _x.header.src.data, _x.header.src_ent.data, _x.header.dst.data, _x.header.dst_ent.data, _x.mask.data, _x.max_depth.data, _x.min_altitude.data, _x.max_altitude.data, _x.min_speed.data, _x.max_speed.data, _x.max_vrate.data, _x.lat.data, _x.lon.data, _x.orientation.data, _x.width.data, _x.length.data,) = _get_struct_3HdHBH2B6f2d3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.rosheader.seq, _x.header.rosheader.stamp.secs, _x.header.rosheader.stamp.nsecs))
      _x = self.header.rosheader.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3HdHBH2B6f2d3f().pack(_x.header.sync.data, _x.header.mgid.data, _x.header.size.data, _x.header.timestamp.data, _x.header.src.data, _x.header.src_ent.data, _x.header.dst.data, _x.header.dst_ent.data, _x.mask.data, _x.max_depth.data, _x.min_altitude.data, _x.max_altitude.data, _x.min_speed.data, _x.max_speed.data, _x.max_vrate.data, _x.lat.data, _x.lon.data, _x.orientation.data, _x.width.data, _x.length.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = imc_ros_msgs.msg.Header()
      if self.mask is None:
        self.mask = std_msgs.msg.UInt8()
      if self.max_depth is None:
        self.max_depth = std_msgs.msg.Float32()
      if self.min_altitude is None:
        self.min_altitude = std_msgs.msg.Float32()
      if self.max_altitude is None:
        self.max_altitude = std_msgs.msg.Float32()
      if self.min_speed is None:
        self.min_speed = std_msgs.msg.Float32()
      if self.max_speed is None:
        self.max_speed = std_msgs.msg.Float32()
      if self.max_vrate is None:
        self.max_vrate = std_msgs.msg.Float32()
      if self.lat is None:
        self.lat = std_msgs.msg.Float64()
      if self.lon is None:
        self.lon = std_msgs.msg.Float64()
      if self.orientation is None:
        self.orientation = std_msgs.msg.Float32()
      if self.width is None:
        self.width = std_msgs.msg.Float32()
      if self.length is None:
        self.length = std_msgs.msg.Float32()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.rosheader.seq, _x.header.rosheader.stamp.secs, _x.header.rosheader.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.rosheader.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.rosheader.frame_id = str[start:end]
      _x = self
      start = end
      end += 73
      (_x.header.sync.data, _x.header.mgid.data, _x.header.size.data, _x.header.timestamp.data, _x.header.src.data, _x.header.src_ent.data, _x.header.dst.data, _x.header.dst_ent.data, _x.mask.data, _x.max_depth.data, _x.min_altitude.data, _x.max_altitude.data, _x.min_speed.data, _x.max_speed.data, _x.max_vrate.data, _x.lat.data, _x.lon.data, _x.orientation.data, _x.width.data, _x.length.data,) = _get_struct_3HdHBH2B6f2d3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3HdHBH2B6f2d3f = None
def _get_struct_3HdHBH2B6f2d3f():
    global _struct_3HdHBH2B6f2d3f
    if _struct_3HdHBH2B6f2d3f is None:
        _struct_3HdHBH2B6f2d3f = struct.Struct("<3HdHBH2B6f2d3f")
    return _struct_3HdHBH2B6f2d3f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
